#!/usr/bin/with-contenv bashio

export PEM_VENTILATION_ENABLED="$(bashio::config 'ventilation_enabled')"
export PEM_TRV_ENABLED="$(bashio::config 'trv_enabled')"
export PEM_WEB_PORT="$(bashio::config 'web_port')"

export VENT_HOUSE_CODE="$(bashio::config 'house_code')"
export VENT_ZONE_IDS="$(bashio::config 'vent_zone_ids')"
export VENT_CHANGE_ONLY_ZONE_IDS="$(bashio::config 'vent_change_only_zone_ids')"
export VENT_ACTIVE_CONTROL="$(bashio::config 'vent_active_control')"
export VENT_POLL_INTERVAL_SECONDS="$(bashio::config 'vent_poll_interval_seconds')"
export VENT_BASELINE_WINDOW_MINUTES="$(bashio::config 'vent_baseline_window_minutes')"
export VENT_BASELINE_MARGIN_GM3="$(bashio::config 'vent_baseline_margin_gm3')"
export VENT_RISE_DELTA_THRESHOLD_GM3="$(bashio::config 'vent_rise_delta_threshold_gm3')"
export VENT_RISE_RATE_THRESHOLD_GM3_PER_MIN="$(bashio::config 'vent_rise_rate_threshold_gm3_per_min')"
export VENT_STABLE_RATE_GM3_PER_MIN="$(bashio::config 'vent_stable_rate_gm3_per_min')"
export VENT_HIGH_RH_GUARD_PERCENT="$(bashio::config 'vent_high_rh_guard_percent')"
export VENT_SENSOR_STALE_MINUTES="$(bashio::config 'vent_sensor_stale_minutes')"
export VENT_MIN_RUNTIME_MINUTES="$(bashio::config 'vent_min_runtime_minutes')"
export VENT_MAX_RUNTIME_MINUTES="$(bashio::config 'vent_max_runtime_minutes')"
export VENT_WEB_PORT="${PEM_WEB_PORT}"
export VENT_HA_URL="http://supervisor/core"
export VENT_HA_TOKEN="${SUPERVISOR_TOKEN}"
export VENT_STATE_PATH="/data/ventilation_manager_state.json"
export VENT_DATABASE_PATH="/data/ventilation_manager_events.sqlite3"

export TRV_HOUSE_CODE="$(bashio::config 'house_code')"
export TRV_ZONE_IDS="$(bashio::config 'trv_zone_ids')"
export TRV_ACTIVE_CONTROL="$(bashio::config 'trv_active_control')"
export TRV_POLL_INTERVAL_SECONDS="$(bashio::config 'trv_poll_interval_seconds')"
export TRV_BASE_DRYING_TARGET_C="$(bashio::config 'trv_base_drying_target_c')"
export TRV_ELEVATED_DRYING_TARGET_C="$(bashio::config 'trv_elevated_drying_target_c')"
export TRV_SEVERE_DRYING_TARGET_C="$(bashio::config 'trv_severe_drying_target_c')"
export TRV_DRYING_ELEVATED_AH_GM3="$(bashio::config 'trv_drying_elevated_absolute_humidity_gm3')"
export TRV_DRYING_SEVERE_AH_GM3="$(bashio::config 'trv_drying_severe_absolute_humidity_gm3')"
export TRV_DRYING_RECOVERED_AH_GM3="$(bashio::config 'trv_drying_recovered_absolute_humidity_gm3')"
export TRV_DRYING_FALLING_RATE_GM3_PER_MIN="$(bashio::config 'trv_drying_falling_rate_gm3_per_min')"
export TRV_HEATING_RESPONSE_WINDOW_MINUTES="$(bashio::config 'trv_heating_response_window_minutes')"
export TRV_HEATING_MIN_EXPECTED_RISE_C="$(bashio::config 'trv_heating_min_expected_rise_c')"
export TRV_WINDOW_DROP_RATE_C_PER_HOUR="$(bashio::config 'trv_window_drop_rate_c_per_hour')"
export TRV_SENSOR_STALE_MINUTES="$(bashio::config 'trv_sensor_stale_minutes')"
export TRV_CALENDAR_POLICY_ENABLED="$(bashio::config 'trv_calendar_policy_enabled')"
export TRV_ACTIVE_CALENDAR_POLICY="$(bashio::config 'trv_active_calendar_policy')"
export TRV_LOCAL_TIMEZONE="$(bashio::config 'trv_local_timezone')"
export TRV_CALENDAR_LOOKBEHIND_DAYS="$(bashio::config 'trv_calendar_lookbehind_days')"
export TRV_CALENDAR_LOOKAHEAD_DAYS="$(bashio::config 'trv_calendar_lookahead_days')"
export TRV_CALENDAR_TRIGGER_TOLERANCE_MINUTES="$(bashio::config 'trv_calendar_trigger_tolerance_minutes')"
export TRV_CALENDAR_CHECKIN_TARGET_C="$(bashio::config 'trv_calendar_checkin_target_c')"
export TRV_CALENDAR_CHECKOUT_TARGET_C="$(bashio::config 'trv_calendar_checkout_target_c')"
export TRV_GUEST_MIN_TARGET_C="$(bashio::config 'trv_guest_min_target_c')"
export TRV_GUEST_MAX_TARGET_C="$(bashio::config 'trv_guest_max_target_c')"
export TRV_GUEST_LIMIT_DELAY_MINUTES="$(bashio::config 'trv_guest_limit_delay_minutes')"
export TRV_SERVICE_BATHROOM_TARGET_C="$(bashio::config 'trv_service_bathroom_target_c')"
export TRV_SERVICE_KITCHEN_TARGET_C="$(bashio::config 'trv_service_kitchen_target_c')"
export TRV_SERVICE_REVERT_DELAY_MINUTES="$(bashio::config 'trv_service_revert_delay_minutes')"
export TRV_FORCE_HEAT_DELAY_MINUTES="$(bashio::config 'trv_force_heat_delay_minutes')"
export TRV_CHILD_LOCK_DELAY_SECONDS="$(bashio::config 'trv_child_lock_delay_seconds')"
export TRV_WEB_PORT="${PEM_WEB_PORT}"
export TRV_HA_URL="http://supervisor/core"
export TRV_HA_TOKEN="${SUPERVISOR_TOKEN}"
export TRV_STATE_PATH="/data/trv_regulator_state.json"
export TRV_DATABASE_PATH="/data/trv_regulator_events.sqlite3"

bashio::log.info "Starting Property Environment Manager for house ${VENT_HOUSE_CODE}"
bashio::log.info "Ventilation enabled=${PEM_VENTILATION_ENABLED}; active_control=${VENT_ACTIVE_CONTROL}"
bashio::log.info "TRV enabled=${PEM_TRV_ENABLED}; active_control=${TRV_ACTIVE_CONTROL}; active_calendar_policy=${TRV_ACTIVE_CALENDAR_POLICY}"

exec python -m property_environment_manager.main
